#!/usr/bin/env sh

if [ -n "$1" ]; then option="$1"; else option="em"; fi
if [ $option = "-h" ]; then printf "Usage: xkcd [OPTION]\ndefault: fetch last comic \n    -r fetch a random comic\n    -h show this message\n"; exit; fi
wget https://xkcd.com/info.0.json -P /tmp > /dev/null 2>&1
if [ $option = "-r" ]; then
	number="$(jq '.num' /tmp/info.0.json)";
	rm /tmp/info.0.json
	randnum="$(shuf -i 1-"$number" -n 1)"
	wget https://xkcd.com/"$randnum"/info.0.json -P /tmp > /dev/null 2>&1
fi
imgurl="$(jq '.img' /tmp/info.0.json | sed 's/\"//g')"
filename="$(echo "$imgurl" | sed 's:.*/::')"
rm /tmp/info.0.json
wget "$imgurl" -P /tmp> /dev/null 2>&1
sxiv "/tmp/$filename"
rm "/tmp/$filename"
